MERGE INTO JHI_AUTHORITY (ID, NAME, DISPLAY_NAME, PARENT_ID)
KEY (ID)
VALUES (1, 'ROLE_ADMIN', 'Administrator', NULL);

MERGE INTO JHI_AUTHORITY (ID, NAME, DISPLAY_NAME, PARENT_ID)
KEY (ID)
VALUES (2, 'ROLE_USER', 'User', NULL);
