DROP TABLE IF EXISTS JHI_RESOURCE_AUTHORITY;
DROP TABLE IF EXISTS JHI_RESOURCE;
DROP TABLE IF EXISTS JHI_USER_AUTHORITY;
DROP TABLE IF EXISTS JHI_USER;
DROP TABLE IF EXISTS JHI_AUTHORITY;
DROP TABLE IF EXISTS JHI_AUDIT_EVENT_DATA;
DROP TABLE IF EXISTS JHI_AUDIT_EVENT;

DROP SEQUENCE IF EXISTS USER_SEQ;
DROP SEQUENCE IF EXISTS RESRC_SEQ;
DROP SEQUENCE IF EXISTS RES_AUTH_SEQ;
DROP SEQUENCE IF EXISTS ADT_EVT_SEQ;

CREATE SEQUENCE USER_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE RESRC_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE RES_AUTH_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE ADT_EVT_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE JHI_AUDIT_EVENT (
                                 EVENT_ID BIGINT NOT NULL,
                                 PRINCIPAL VARCHAR(255) NOT NULL,
                                 EVENT_DATE TIMESTAMP,
                                 EVENT_TYPE VARCHAR(255),
                                 PRIMARY KEY (EVENT_ID)
);

CREATE TABLE JHI_AUDIT_EVENT_DATA (
                                      EVENT_ID BIGINT NOT NULL,
                                      NAME VARCHAR(255) NOT NULL,
                                      VALUE VARCHAR(255)
);

CREATE TABLE JHI_AUTHORITY (
                               ID BIGINT NOT NULL,
                               NAME VARCHAR(50) NOT NULL,
                               DISPLAY_NAME VARCHAR(300),
                               PARENT_ID BIGINT,
                               PRIMARY KEY (ID)
);

CREATE TABLE JHI_USER (
                          ID BIGINT NOT NULL,
                          LOGIN VARCHAR(50) NOT NULL,
                          PASSWORD_HASH VARCHAR(60) NOT NULL,
                          FIRST_NAME VARCHAR(50),
                          LAST_NAME VARCHAR(50),
                          EMAIL VARCHAR(254),
                          ACTIVATED BOOLEAN NOT NULL,
                          LANG_KEY VARCHAR(10),
                          IMAGE_URL VARCHAR(256),
                          ACTIVATION_KEY VARCHAR(20),
                          RESET_KEY VARCHAR(20),
                          RESET_DATE TIMESTAMP,
                          PARTY_ID VARCHAR(250),
                          CREATED_BY VARCHAR(50) NOT NULL,
                          CREATED_DATE TIMESTAMP,
                          LAST_MODIFIED_BY VARCHAR(50),
                          LAST_MODIFIED_DATE TIMESTAMP,
                          PRIMARY KEY (ID)
);

CREATE TABLE JHI_USER_AUTHORITY (
                                    USER_ID BIGINT NOT NULL,
                                    AUTHORITY_ID BIGINT NOT NULL
);

CREATE TABLE JHI_RESOURCE (
                              ID BIGINT NOT NULL,
                              NAME VARCHAR(200) NOT NULL,
                              DISPLAY_NAME VARCHAR(300) NOT NULL,
                              API_URI VARCHAR(1000) NOT NULL,
                              RESOURCE_TYPE VARCHAR(255) NOT NULL,
                              PRIMARY KEY (ID)
);

CREATE TABLE JHI_RESOURCE_AUTHORITY (
                                        ID BIGINT NOT NULL,
                                        VERB VARCHAR(255) NOT NULL,
                                        AUTHORITY_ID BIGINT NOT NULL,
                                        RESOURCE_ID BIGINT NOT NULL,
                                        PRIMARY KEY (ID)
);

ALTER TABLE JHI_AUDIT_EVENT_DATA
    ADD CONSTRAINT FK_JHI_AUDIT_EVENT_DATA_EVENT_ID
        FOREIGN KEY (EVENT_ID)
            REFERENCES JHI_AUDIT_EVENT (EVENT_ID);

ALTER TABLE JHI_AUTHORITY
    ADD CONSTRAINT UK_JHI_AUTHORITY_NAME
        UNIQUE (NAME);

ALTER TABLE JHI_AUTHORITY
    ADD CONSTRAINT FK_JHI_AUTHORITY_PARENT_ID
        FOREIGN KEY (PARENT_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_USER
    ADD CONSTRAINT UK_JHI_USER_LOGIN
        UNIQUE (LOGIN);

ALTER TABLE JHI_USER
    ADD CONSTRAINT UK_JHI_USER_EMAIL
        UNIQUE (EMAIL);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT PK_JHI_USER_AUTHORITY
        PRIMARY KEY (USER_ID, AUTHORITY_ID);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT FK_JHI_USER_AUTHORITY_USER_ID
        FOREIGN KEY (USER_ID)
            REFERENCES JHI_USER (ID);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT FK_JHI_USER_AUTHORITY_AUTHORITY_ID
        FOREIGN KEY (AUTHORITY_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_RESOURCE_AUTHORITY
    ADD CONSTRAINT FK_JHI_RESOURCE_AUTHORITY_AUTHORITY_ID
        FOREIGN KEY (AUTHORITY_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_RESOURCE_AUTHORITY
    ADD CONSTRAINT FK_JHI_RESOURCE_AUTHORITY_RESOURCE_ID
        FOREIGN KEY (RESOURCE_ID)
            REFERENCES JHI_RESOURCE (ID);
