CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS RESRC_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS RES_AUTH_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ADT_EVT_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS JHI_AUDIT_EVENT (
                                               EVENT_ID BIGINT NOT NULL,
                                               PRINCIPAL VARCHAR(255) NOT NULL,
    EVENT_DATE TIMESTAMP,
    EVENT_TYPE VARCHAR(255),
    PRIMARY KEY (EVENT_ID)
    );

CREATE TABLE IF NOT EXISTS JHI_AUDIT_EVENT_DATA (
                                                    EVENT_ID BIGINT NOT NULL,
                                                    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS JHI_AUTHORITY (
                                             ID BIGINT NOT NULL,
                                             NAME VARCHAR(50) NOT NULL,
    DISPLAY_NAME VARCHAR(300),
    PARENT_ID BIGINT,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS JHI_USER (
                                        ID BIGINT NOT NULL,
                                        LOGIN VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(60) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(254),
    ACTIVATED BOOLEAN NOT NULL,
    LANG_KEY VARCHAR(10),
    IMAGE_URL VARCHAR(256),
    ACTIVATION_KEY VARCHAR(20),
    RESET_KEY VARCHAR(20),
    RESET_DATE TIMESTAMP,
    PARTY_ID VARCHAR(250),
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(50),
    LAST_MODIFIED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS JHI_USER_AUTHORITY (
                                                  USER_ID BIGINT NOT NULL,
                                                  AUTHORITY_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS JHI_RESOURCE (
                                            ID BIGINT NOT NULL,
                                            NAME VARCHAR(200) NOT NULL,
    DISPLAY_NAME VARCHAR(300) NOT NULL,
    API_URI VARCHAR(1000) NOT NULL,
    RESOURCE_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS JHI_RESOURCE_AUTHORITY (
                                                      ID BIGINT NOT NULL,
                                                      VERB VARCHAR(255) NOT NULL,
    AUTHORITY_ID BIGINT NOT NULL,
    RESOURCE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID)
    );
