DROP TABLE IF EXISTS JHI_RESOURCE_AUTHORITY;
DROP TABLE IF EXISTS JHI_RESOURCE;
DROP TABLE IF EXISTS JHI_USER_AUTHORITY;
DROP TABLE IF EXISTS JHI_USER;
DROP TABLE IF EXISTS JHI_AUTHORITY;
DROP TABLE IF EXISTS JHI_AUDIT_EVENT_DATA;
DROP TABLE IF EXISTS JHI_AUDIT_EVENT;

DROP SEQUENCE IF EXISTS USER_SEQ;
DROP SEQUENCE IF EXISTS RESRC_SEQ;
DROP SEQUENCE IF EXISTS RES_AUTH_SEQ;
DROP SEQUENCE IF EXISTS ADT_EVT_SEQ;

CREATE SEQUENCE USER_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE RESRC_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE RES_AUTH_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE ADT_EVT_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE JHI_AUDIT_EVENT (
                                 EVENT_ID BIGINT NOT NULL,
                                 PRINCIPAL VARCHAR(255) NOT NULL,
                                 EVENT_DATE TIMESTAMP,
                                 EVENT_TYPE VARCHAR(255),
                                 PRIMARY KEY (EVENT_ID)
);

CREATE TABLE JHI_AUDIT_EVENT_DATA (
                                      EVENT_ID BIGINT NOT NULL,
                                      NAME VARCHAR(255) NOT NULL,
                                      VALUE VARCHAR(255)
);

CREATE TABLE JHI_AUTHORITY (
                               ID BIGINT NOT NULL,
                               NAME VARCHAR(50) NOT NULL,
                               DISPLAY_NAME VARCHAR(300),
                               PARENT_ID BIGINT,
                               PRIMARY KEY (ID)
);

CREATE TABLE JHI_USER (
                          ID BIGINT NOT NULL,
                          LOGIN VARCHAR(50) NOT NULL,
                          PASSWORD_HASH VARCHAR(60) NOT NULL,
                          FIRST_NAME VARCHAR(50),
                          LAST_NAME VARCHAR(50),
                          EMAIL VARCHAR(254),
                          ACTIVATED BOOLEAN NOT NULL,
                          LANG_KEY VARCHAR(10),
                          IMAGE_URL VARCHAR(256),
                          ACTIVATION_KEY VARCHAR(20),
                          RESET_KEY VARCHAR(20),
                          RESET_DATE TIMESTAMP,
                          PARTY_ID VARCHAR(250),
                          CREATED_BY VARCHAR(50) NOT NULL,
                          CREATED_DATE TIMESTAMP,
                          LAST_MODIFIED_BY VARCHAR(50),
                          LAST_MODIFIED_DATE TIMESTAMP,
                          PRIMARY KEY (ID)
);

CREATE TABLE JHI_USER_AUTHORITY (
                                    USER_ID BIGINT NOT NULL,
                                    AUTHORITY_ID BIGINT NOT NULL
);

CREATE TABLE JHI_RESOURCE (
                              ID BIGINT NOT NULL,
                              NAME VARCHAR(200) NOT NULL,
                              DISPLAY_NAME VARCHAR(300) NOT NULL,
                              API_URI VARCHAR(1000) NOT NULL,
                              RESOURCE_TYPE VARCHAR(255) NOT NULL,
                              PRIMARY KEY (ID)
);

CREATE TABLE JHI_RESOURCE_AUTHORITY (
                                        ID BIGINT NOT NULL,
                                        VERB VARCHAR(255) NOT NULL,
                                        AUTHORITY_ID BIGINT NOT NULL,
                                        RESOURCE_ID BIGINT NOT NULL,
                                        PRIMARY KEY (ID)
);

ALTER TABLE JHI_AUDIT_EVENT_DATA
    ADD CONSTRAINT FK_JHI_AUDIT_EVENT_DATA_EVENT_ID
        FOREIGN KEY (EVENT_ID)
            REFERENCES JHI_AUDIT_EVENT (EVENT_ID);

ALTER TABLE JHI_AUTHORITY
    ADD CONSTRAINT UK_JHI_AUTHORITY_NAME
        UNIQUE (NAME);

ALTER TABLE JHI_AUTHORITY
    ADD CONSTRAINT FK_JHI_AUTHORITY_PARENT_ID
        FOREIGN KEY (PARENT_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_USER
    ADD CONSTRAINT UK_JHI_USER_LOGIN
        UNIQUE (LOGIN);

ALTER TABLE JHI_USER
    ADD CONSTRAINT UK_JHI_USER_EMAIL
        UNIQUE (EMAIL);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT PK_JHI_USER_AUTHORITY
        PRIMARY KEY (USER_ID, AUTHORITY_ID);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT FK_JHI_USER_AUTHORITY_USER_ID
        FOREIGN KEY (USER_ID)
            REFERENCES JHI_USER (ID);

ALTER TABLE JHI_USER_AUTHORITY
    ADD CONSTRAINT FK_JHI_USER_AUTHORITY_AUTHORITY_ID
        FOREIGN KEY (AUTHORITY_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_RESOURCE_AUTHORITY
    ADD CONSTRAINT FK_JHI_RESOURCE_AUTHORITY_AUTHORITY_ID
        FOREIGN KEY (AUTHORITY_ID)
            REFERENCES JHI_AUTHORITY (ID);

ALTER TABLE JHI_RESOURCE_AUTHORITY
    ADD CONSTRAINT FK_JHI_RESOURCE_AUTHORITY_RESOURCE_ID
        FOREIGN KEY (RESOURCE_ID)
            REFERENCES JHI_RESOURCE (ID);

-- Mediation domain tables.
-- Entities use @Table(name = "MEDIATION.TBL_...") so Hibernate validates a *literal*
-- table name that includes the dot (not schema MEDIATION + table TBL_...).
-- H2 therefore needs quoted identifiers matching those names (and lowercase variants).

DROP TABLE IF EXISTS "MEDIATION.TBL_FLOWS";
DROP TABLE IF EXISTS "MEDIATION.TBL_CONFIGS";
DROP TABLE IF EXISTS "MEDIATION.tbl_configs";
DROP TABLE IF EXISTS "MEDIATION.TBL_MODULES";
DROP TABLE IF EXISTS "MEDIATION.tbl_modules";
DROP TABLE IF EXISTS "MEDIATION.TBL_PRODUCTS";
DROP TABLE IF EXISTS "MEDIATION.tbl_products";
DROP TABLE IF EXISTS "MEDIATION.TBL_INSTANCES";
DROP TABLE IF EXISTS "MEDIATION.TBL_VERSIONS";
DROP TABLE IF EXISTS "MEDIATION.tbl_versions";
DROP TABLE IF EXISTS "MEDIATION.TBL_LOGS";
DROP TABLE IF EXISTS "MEDIATION.tbl_logs";

DROP SEQUENCE IF EXISTS "MEDIATION.FLOWS_SEQ";
DROP SEQUENCE IF EXISTS "MEDIATION.PRODUCTS_SEQ";
DROP SEQUENCE IF EXISTS MODULES_SEQ;
DROP SEQUENCE IF EXISTS CONFIGS_SEQ;
DROP SEQUENCE IF EXISTS LOG_SEQ;
DROP SEQUENCE IF EXISTS "sequenceGenerator";
DROP SEQUENCE IF EXISTS SEQUENCEGENERATOR;

CREATE SEQUENCE "MEDIATION.FLOWS_SEQ" START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE "MEDIATION.PRODUCTS_SEQ" START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE MODULES_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE CONFIGS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE LOG_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE "sequenceGenerator" START WITH 1000 INCREMENT BY 50;
CREATE SEQUENCE SEQUENCEGENERATOR START WITH 1000 INCREMENT BY 50;

-- Exact names from @Table annotations (case-sensitive via quotes)
CREATE TABLE "MEDIATION.tbl_products" (
    PRODUCT_KEY BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(3) NOT NULL,
    PRODUCT_DESC VARCHAR(300) NOT NULL,
    PRIMARY KEY (PRODUCT_KEY)
);
ALTER TABLE "MEDIATION.tbl_products" ADD CONSTRAINT UK_MED_PRODUCTS_NAME UNIQUE (PRODUCT_NAME);

CREATE TABLE "MEDIATION.TBL_FLOWS" (
    FLOW_KEY BIGINT NOT NULL,
    FLOW_NAME VARCHAR(6) NOT NULL,
    FLOW_DESC VARCHAR(300) NOT NULL,
    FLOW CLOB NOT NULL,
    PRODUCT_NAME VARCHAR(3) NOT NULL,
    PRIMARY KEY (FLOW_KEY)
);
ALTER TABLE "MEDIATION.TBL_FLOWS" ADD CONSTRAINT FK_MED_FLOWS_PRODUCT
    FOREIGN KEY (PRODUCT_NAME) REFERENCES "MEDIATION.tbl_products" (PRODUCT_NAME);

CREATE TABLE "MEDIATION.tbl_modules" (
    MODULE_KEY BIGINT NOT NULL,
    MODULE_NAME VARCHAR(50) NOT NULL,
    DEFAULT_PORT VARCHAR(4) NOT NULL,
    REDIS_KEY_PREFIX VARCHAR(5) NOT NULL,
    STATUS BIGINT NOT NULL,
    LOGGING_MODE VARCHAR(255) NOT NULL,
    LOGGING_FILTER VARCHAR(500),
    DNS_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (MODULE_KEY)
);
ALTER TABLE "MEDIATION.tbl_modules" ADD CONSTRAINT UK_MED_MODULES_NAME UNIQUE (MODULE_NAME);

CREATE TABLE "MEDIATION.tbl_configs" (
    CONFIG_KEY BIGINT NOT NULL,
    PROPERTY VARCHAR(100) NOT NULL,
    P_VALUE VARCHAR(300) NOT NULL,
    COMMENT_DESC VARCHAR(200),
    MODULE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (CONFIG_KEY)
);
ALTER TABLE "MEDIATION.tbl_configs" ADD CONSTRAINT FK_MED_CONFIGS_MODULE
    FOREIGN KEY (MODULE_NAME) REFERENCES "MEDIATION.tbl_modules" (MODULE_NAME);

CREATE TABLE "MEDIATION.TBL_INSTANCES" (
    INSTANCE_KEY BIGINT NOT NULL,
    MODULE_NAME VARCHAR(50) NOT NULL,
    PORT VARCHAR(10) NOT NULL,
    MODULE_STATUS VARCHAR(50) NOT NULL,
    LAST_UPDATE_DATE DATE NOT NULL,
    THREAD_POOL_QUEUE_SIZE BIGINT,
    MODULE_START_TIME BIGINT,
    TOTAL_PROCESSED_WORK BIGINT,
    TOTAL_PROCESSED_TASK BIGINT,
    PROCESSED_STATISTICS CLOB,
    HOST_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (INSTANCE_KEY)
);

CREATE TABLE "MEDIATION.tbl_versions" (
    VERSION_KEY BIGINT NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    MODULE_NAME VARCHAR(50) NOT NULL,
    TABLE_VERSION BIGINT NOT NULL,
    PRIMARY KEY (VERSION_KEY)
);

CREATE TABLE "MEDIATION.tbl_logs" (
    LOG_KEY BIGINT NOT NULL,
    LOG_TYPE VARCHAR(100),
    MSG_TYPE VARCHAR(100),
    CORRELATION_ID VARCHAR(100),
    SEND_ID VARCHAR(50),
    REFERENCE_TYPE VARCHAR(100),
    REFERENCE VARCHAR(100),
    IS_VALIDATE BIGINT,
    INITIAL_DATE TIMESTAMP,
    CREATE_DATE TIMESTAMP,
    EXPIRE_DATE TIMESTAMP,
    MODULE_SOURCE VARCHAR(50),
    MODULE_DESTINATION VARCHAR(50),
    SOURCE_INSTANCE VARCHAR(300),
    DESTINATION_INSTANCE VARCHAR(100),
    ERROR VARCHAR(200),
    BUSINESS_ERROR_DESC VARCHAR(300),
    BACKEND_ERROR_DESC VARCHAR(300),
    ERROR_DETAILS VARCHAR(4000),
    CHECK_FLAG BIGINT,
    INSERT_DATE TIMESTAMP,
    PROPERTIES CLOB,
    REQ_MESSAGE CLOB,
    RES_MESSAGE CLOB,
    RETRY_MODE VARCHAR(100),
    RETRY_COUNT BIGINT,
    RETRY_DESTINATION_MODULE VARCHAR(50),
    COMMENT_DESC VARCHAR(200),
    PRIMARY KEY (LOG_KEY)
);
